// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/gardener/gardener/pkg/apis/core/v1beta1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// SeedBindingLister helps list SeedBindings.
// All objects returned here must be treated as read-only.
type SeedBindingLister interface {
	// List lists all SeedBindings in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.SeedBinding, err error)
	// SeedBindings returns an object that can list and get SeedBindings.
	SeedBindings(namespace string) SeedBindingNamespaceLister
	SeedBindingListerExpansion
}

// seedBindingLister implements the SeedBindingLister interface.
type seedBindingLister struct {
	indexer cache.Indexer
}

// NewSeedBindingLister returns a new SeedBindingLister.
func NewSeedBindingLister(indexer cache.Indexer) SeedBindingLister {
	return &seedBindingLister{indexer: indexer}
}

// List lists all SeedBindings in the indexer.
func (s *seedBindingLister) List(selector labels.Selector) (ret []*v1beta1.SeedBinding, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.SeedBinding))
	})
	return ret, err
}

// SeedBindings returns an object that can list and get SeedBindings.
func (s *seedBindingLister) SeedBindings(namespace string) SeedBindingNamespaceLister {
	return seedBindingNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// SeedBindingNamespaceLister helps list and get SeedBindings.
// All objects returned here must be treated as read-only.
type SeedBindingNamespaceLister interface {
	// List lists all SeedBindings in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.SeedBinding, err error)
	// Get retrieves the SeedBinding from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.SeedBinding, error)
	SeedBindingNamespaceListerExpansion
}

// seedBindingNamespaceLister implements the SeedBindingNamespaceLister
// interface.
type seedBindingNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all SeedBindings in the indexer for a given namespace.
func (s seedBindingNamespaceLister) List(selector labels.Selector) (ret []*v1beta1.SeedBinding, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.SeedBinding))
	})
	return ret, err
}

// Get retrieves the SeedBinding from the indexer for a given namespace and name.
func (s seedBindingNamespaceLister) Get(name string) (*v1beta1.SeedBinding, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1beta1.Resource("seedbinding"), name)
	}
	return obj.(*v1beta1.SeedBinding), nil
}
